services:
  registry:
    image: registry:latest
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      # Mount the password file
      - ./registry.password:/auth/registry.password
      # Mount the data directory
      - ./data:/data
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    depends_on:
      - registry
    volumes:
      # mount the nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf
      # mount the certificates obtained from Let's Encrypt
      - ./ssl-certs:/etc/nginx/certs
    ports:
      - "443:443"