services:
  local-container-registry:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-container-registry:latest
    container_name: local-container-registry
    environment:
      DATABASE_URL: "host=local_container_registry_db user=postgres password=postgres port=5433 dbname=postgres sslmode=disable"
    ports:
      - "8081:8081"
    depends_on:
      - local_container_registry_db
  local_container_registry_db:
    image: postgres:12
    container_name: local_container_registry_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata: {}
